adsdroid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from rest_framework.documentation import get_schemajs_view, include_docs_urls

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("openai/", include("apps.openai_api.urls")),
    path("sp-api/", include("apps.sp_api.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    # these are needed for schema.js
    path("docs/", include_docs_urls(title="API Docs")),
    path("schemajs/", schemajs_view, name="api_schemajs"),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    path(
        "favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("images/favicons/favicon-16x16.png"))
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sp_api/urls.py
from django.urls import path

from .views import get_book_catalog

app_name = "openai"

urlpatterns = [
    path("get-book-catalog/", get_book_catalog, name="get_book_catalog"),
]

pegasus/apps/employees/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

app_name = "pegasus_employees"

urlpatterns = [
    path(
        "objects/",
        TemplateView.as_view(
            template_name="pegasus/employees/object_lifecycle_home.html",
            extra_context={"active_tab": "object_lifecycle"},
        ),
        name="object_lifecycle_home",
    ),
    path("objects/django/", views.employee_list, name="django_object_lifecycle"),
    path("objects/django/new/", views.new_employee, name="django_new_employee"),
    path("objects/django/edit/<int:employee_id>/", views.edit_employee, name="django_edit_employee"),
    path("objects/django/delete/<int:employee_id>/", views.delete_employee, name="django_delete_employee"),
    path("objects/htmx/", views.employee_list_htmx, name="htmx_object_lifecycle"),
    path("objects/htmx/new/", views.new_employee_row_htmx, name="htmx_new_employee"),
    path("objects/htmx/empty/", views.empty_htmx, name="htmx_empty"),
    path("objects/htmx/edit/<int:employee_id>/", views.edit_employee_row_htmx, name="htmx_edit_employee"),
    path("objects/htmx/get/<int:employee_id>/", views.get_employee_row_htmx, name="htmx_get_employee"),
    path("objects/htmx/delete/<int:employee_id>/", views.delete_employee_htmx, name="htmx_delete_employee"),
    path("objects/react/", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle"),
    path("objects/react/<path:path>", views.ReactObjectLifecycleView.as_view(), name="react_object_lifecycle_w_path"),
    path("objects/vue/", views.VueObjectLifecycleView.as_view(), name="vue_object_lifecycle"),
    path("charts/", views.ChartsView.as_view(), name="charts"),
    path("api/employee-data/", views.EmployeeDataAPIView.as_view(), name="employee_data"),
    path("objects/profiles/", views.profiles_list_htmx, name="htmx_profiles_list"),
    path("objects/profiles_table/", views.create_profiles_table, name="htmx_profiles_table"),
    path("objects/related/", views.relevant_table, name="relevant_table"),
    path("objects/htmx/relevant/<int:rel_id>/<str:relevant_bool>/", views.set_relevant, name="set_relevant"),
    path("objects/htmx/set_relevant_table/<str:table_type>/", views.set_relevant_table, name="set_relevant_table"),
]


# drf config
router = routers.DefaultRouter()
router.register("api/employees", views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/employees/models.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employees')
    name = models.CharField(max_length=100, help_text="Your employee's name.")
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES,
                                  help_text='What department your employee belongs to.')
    salary = models.PositiveIntegerField(help_text="Your employee's annual salary.")

    def __str__(self):
        return self.name

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("name", "department", "salary")

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, Sum
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods, require_POST
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.ads_api.models import Profile, Relevance
from apps.api.helpers import get_user_from_request
from apps.api.permissions import IsAuthenticatedOrHasUserAPIKey

from .forms import EmployeeForm
from .models import Employee
from .serializers import EmployeeSerializer


@login_required
def employee_list(request):
    return render(
        request,
        "pegasus/employees/list_employees.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):  # type: ignore
    if employee:
        assert employee.user == request.user
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user  # type: ignore
            employee.save()  # type: ignore
            return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/edit_employee.html",
        {
            "active_tab": "object_lifecycle",
            "employee": employee,
            "form": form,
        },
    )


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse("pegasus_employees:django_object_lifecycle"))


@login_required
def employee_list_htmx(request):
    return render(
        request,
        "pegasus/employees/htmx_object_lifecycle.html",
        {"active_tab": "object_lifecycle", "employees": Employee.objects.filter(user=request.user)},
    )


@login_required
def profiles_list_htmx(request):
    return render(
        request,
        "pegasus/employees/htmx_profiles_list.html",
        {
            "active_tab": "object_lifecycle",
            "profiles": Profile.objects.filter(managed=True).order_by("nickname"),
        },
    )


def create_profiles_table(request, managed_bool="Yes"):
    managed_bool = request.POST.get("id")
    managed_bool = True if managed_bool == "Yes" else False
    return render(
        request,
        "pegasus/employees/profiles_table.html",
        {
            "profiles": Profile.objects.filter(managed=managed_bool).order_by("nickname"),
        },
    )


def relevant_table(request):
    return render(
        request,
        "pegasus/employees/related_table.html",
        {
            "relevants": Relevance.objects.all(),
        },
    )


def set_relevant(request, rel_id, relevant_bool):
    rel = Relevance.objects.get(pk=rel_id)
    rel.relevant = True if relevant_bool == "True" else False
    rel.save()

    return render(
        request,
        "pegasus/employees/htmx/relevancy_checkbox.html",
        {
            "relevant": rel,
            "checkbox": relevant_bool,
        },
    )


def set_relevant_table(request, table_type: str):
    if table_type == "show_all":
        relevants = Relevance.objects.all()
    else:
        relevants = Relevance.objects.filter(relevant=False, checked=False)

    return render(
        request,
        "pegasus/employees/related_table_loop.html",
        {
            "relevants": relevants,
        },
    )


@login_required
def new_employee_row_htmx(request):
    return _add_edit_employee_htmx(request)


@login_required
def edit_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee_htmx(request, employee)


def _add_edit_employee_htmx(request, employee=None):
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse("pegasus_employees:htmx_get_employee", args=[employee.id]))
    else:
        form = EmployeeForm(instance=employee)

    return render(
        request,
        "pegasus/employees/htmx/edit_employee_row.html",
        {
            "employee": employee,
            "form": form,
        },
    )


def empty_htmx(request):
    return HttpResponse("")


@login_required
def get_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return render(
        request,
        "pegasus/employees/htmx/employee_row.html",
        {
            "employee": employee,
        },
    )


@require_http_methods(["DELETE"])
@login_required
def delete_employee_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponse("")


@method_decorator(login_required, name="dispatch")
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            "department_choices": [{"id": c[0], "name": c[1]} for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/react_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://reactjs.org/",
                "framework_name": "React",
                "framework_icon": static("images/pegasus/react-icon.png"),
                "active_tab": "object_lifecycle",
                "url_base": reverse("pegasus_employees:react_object_lifecycle"),
            }  # type: ignore
        )
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = "pegasus/employees/vue_object_lifecycle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "framework_url": "https://vuejs.org/",
                "framework_name": "Vue.js",
                "framework_icon": static("images/pegasus/vue-icon.png"),
                "active_tab": "object_lifecycle",
                "url_base": reverse("pegasus_employees:vue_object_lifecycle"),
            }  # type: ignore
        )
        return context


@method_decorator(login_required, name="dispatch")
class ChartsView(TemplateView):
    template_name = "pegasus/employees/charts.html"

    def get_context_data(self, **kwargs):
        return {
            "active_tab": "charts",
        }


class EmployeeDataAPIView(APIView):
    permission_classes = (IsAuthenticatedOrHasUserAPIKey,)

    def get(self, request):
        user = get_user_from_request(request)
        data = user.employees.values("department").annotate(  # type: ignore
            average_salary=Avg("salary"),
            total_cost=Sum("salary"),
            number_employees=Count("pk"),
        )  # type: ignore
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [[row["department"], row["total_cost"]] for row in data]
        average_salaries = [[row["department"], row["average_salary"]] for row in data]
        headcounts = [[row["department"], row["number_employees"]] for row in data]
        return Response(
            {
                "total_costs": total_costs,
                "average_salaries": average_salaries,
                "headcounts": headcounts,
            }
        )


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()  # type: ignore

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

templates/pegasus/employees/htmx/edit_employee_row.html
{% load form_tags %}
<form class="tr" hx-post="{% if employee %}{% url 'pegasus_employees:htmx_edit_employee' employee.id %}{% else %}{% url 'pegasus_employees:htmx_new_employee' %}{% endif %}"
      hx-target="this" hx-swap="outerHTML">
  {% csrf_token %}
  <div class="td pg-input-group">
    {{ form.name }}
    {{ form.name.errors }}
  </div>
  <div class="td">
    <div class="select">{{ form.department }}</div>
  </div>
  <div class="td pg-input-group">
    {{ form.salary }}
    {{ form.salary.errors }}
  </div>
  <div class="td" >
    <div class="pg-inline-buttons pg-justify-content-end pg-align-items-center">
    <button class="pg-button-primary" type="submit">
      <span class="icon is-small"><i class="fa fa-save"></i></span>
      <span>Save</span>
    </button>
    {% if employee %}
      <button class="pg-button-secondary pg-ml" hx-get="{% url 'pegasus_employees:htmx_get_employee' employee.id %}">Cancel</button>
    {% else %}
      <button class="pg-button-secondary pg-ml" hx-get="{% url 'pegasus_employees:htmx_empty' %}">Cancel</button>
    {% endif %}
    </div>
  </div>
</form>
{% if not employee and not form.errors %}
  {% include 'pegasus/employees/htmx/new_employee_button.html' %}
{% endif %}

templates/pegasus/employees/htmx/employee_row.html
<div class="tr" hx-target="this" hx-swap="outerHTML">
  <div class="td">{{ employee.name }}</div>
  <div class="td">{{ employee.get_department_display }}</div>
  <div class="td pg-text-right">${{ employee.salary }}</div>
  <div class="td pg-inline-buttons pg-justify-content-end">
    <div class="pg-button-secondary" hx-get="{% url 'pegasus_employees:htmx_edit_employee' employee.id %}">
      <span class="icon is-small"><i class="fa fa-edit"></i></span>
      <span class="pg-hidden-mobile-inline">Edit</span>
    </div>
    <button class="pg-button-danger pg-ml" type="submit" hx-delete="{% url 'pegasus_employees:htmx_delete_employee' employee.id %}">
      <span class="icon is-small"><i class="fa fa-times"></i></span>
      <span>Delete</span>
    </button>
  </div>
</div>

templates/pegasus/employees/htmx/new_employee_button.html
<div class="mt-2" hx-target="this" hx-swap="outerHTML">
  <a class="pg-button-primary" hx-get="{% url 'pegasus_employees:htmx_new_employee' %}">
    <span class="icon is-small"><i class="fa fa-plus"></i></span>
    <span>Add Employee</span>
  </a>
</div>

templates/pegasus/employees/htmx/profile_row.html
<div class="tr" hx-target="this" hx-swap="outerHTML">
  <div class="td">{{ profile.nickname }}</div>
  <div class="td">{{ profile.country_code }}</div>
  <div class="td">{{ profile.entity_id }}</div>
  <div class="td">{{ profile.managed }}</div>
</div>

templates/pegasus/employees/htmx/relevancy_checkbox.html
{% if checkbox == "True" %}
    <input type="checkbox"
           checked="checked"
           hx-post="{% url 'pegasus_employees:set_relevant' rel_id=relevant.id relevant_bool='False' %}"
           hx-trigger="click"
           hx-swap="outerHTML"
           hx-target="this">
{% else %}
    <input type="checkbox"
           hx-post="{% url 'pegasus_employees:set_relevant' rel_id=relevant.id relevant_bool='True' %}"
           hx-trigger="click"
           hx-swap="outerHTML"
           hx-target="this">
{% endif %}

templates/pegasus/employees/htmx/relevancy_row.html
<tr>
    <td>
        <p class="text-xs font-weight-bold mb-0">{{ relevant.book }}</p>
    </td>
    <td>
        <div class="d-flex px-2 py-1">
            <div>
                <img src={{ relevant.new_release.image_url }} class="avatar avatar-sm me-3">
            </div>
            <div class="d-flex flex-column justify-content-center">
                <h6 class="mb-0 text-xs">{{ relevant.new_release.title }}</h6>
            </div>
        </div>
    </td>
    <td>
        <p class="text-xs font-weight-bold mb-0">{{ relevant.new_release }}</p>
    </td>
    <td class="align-middle text-center">
        {% if relevant.relevant %}
            <input type="checkbox"
                   checked="checked"
                   hx-post="{% url 'pegasus_employees:set_relevant' relevant.id "False" %}"
                   hx-trigger="click"
                   hx-swap="outerHTML"
                   hx-target="this">
        {% else %}
            <input type="checkbox"
                   hx-post="{% url 'pegasus_employees:set_relevant' relevant.id "True" %}"
                   hx-trigger="click"
                   hx-swap="outerHTML"
                   hx-target="this">
        {% endif %}
    </td>
    <td class="align-middle text-center">
        {% if relevant.checked %}
            <input type="checkbox" checked="checked">
        {% else %}
            <input type="checkbox">
        {% endif %}
    </td>
    <td class="align-middle text-center">
        {% if relevant.targeting %}
            <input type="checkbox" checked="checked">
        {% else %}
            <input type="checkbox">
        {% endif %}
    </td>
</tr>